# Generated by Django 4.1.3 on 2023-01-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.CharField(max_length=20, verbose_name="기준날짜")),
                ("krw2usd", models.CharField(max_length=20, verbose_name="달러")),
                ("jpy2usd", models.CharField(max_length=20, verbose_name="엔화")),
            ],
        ),
    ]
