# Generated by Django 4.1.3 on 2022-11-17 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('enter_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('army_type', models.CharField(blank=True, choices=[('army', '육군'), ('navy', '해군'), ('air', '공군')], max_length=30, null=True)),
            ],
        ),
    ]
