# Generated by Django 4.1.3 on 2022-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(default='password', max_length=20)),
                ('enter_date', models.DateTimeField()),
                ('army_choice', models.CharField(choices=[('육군', '육군'), ('해군', '해군'), ('공군', '공군'), ('해병대', '해병대'), ('공익', '공익')], max_length=30, null=True)),
                ('bio', models.CharField(blank=True, default='한줄소개', max_length=200, null=True)),
            ],
        ),
    ]
