# Generated by Django 4.1.3 on 2022-12-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_gundori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
