# Generated by Django 4.1.3 on 2022-11-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_gundori', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='army_type',
            new_name='army_choice',
        ),
    ]
