# Generated by Django 4.1.3 on 2022-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_gundori', '0002_rename_army_type_soldier_army_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='army_choice',
            field=models.CharField(choices=[('army', '육군'), ('navy', '해군'), ('air', '공군')], max_length=30),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='enter_date',
            field=models.DateTimeField(),
        ),
    ]
