# Generated by Django 4.1.3 on 2022-12-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fake_gundori", "0002_alter_soldier_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soldier",
            name="army_choice",
            field=models.CharField(
                choices=[
                    ("육군", "육군"),
                    ("해군", "해군"),
                    ("공군", "공군"),
                    ("해병대", "해병대"),
                    ("공익", "공익"),
                ],
                max_length=30,
                null=True,
                verbose_name="복무선택",
            ),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="bio",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="한줄소개"
            ),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="enter_date",
            field=models.DateTimeField(verbose_name="입대일"),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="name",
            field=models.CharField(max_length=20, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="password",
            field=models.CharField(max_length=20, verbose_name="비밀번호"),
        ),
    ]
