# Generated by Django 4.1.3 on 2022-11-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_gundori', '0003_alter_soldier_army_choice_alter_soldier_enter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='army_choice',
            field=models.CharField(choices=[('army', '육군'), ('navy', '해군'), ('air', '공군')], max_length=30, null=True),
        ),
    ]
