# Generated by Django 4.1.3 on 2022-12-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fake_gundori", "0003_alter_soldier_army_choice_alter_soldier_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soldier",
            name="password",
            field=models.CharField(
                default="password", max_length=20, verbose_name="비밀번호"
            ),
        ),
    ]
