# Generated by Django 4.1.3 on 2022-11-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_gundori', '0004_alter_soldier_army_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='bio',
            field=models.CharField(blank=True, default='한줄소개', max_length=200, null=True),
        ),
    ]
