# Generated by Django 4.1.3 on 2022-11-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_gundori', '0005_soldier_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
